<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Roshan99" failures="1" tests="9" name="XYZ Bank Test" time="102.071" errors="0" timestamp="2024-03-07T22:52:13 IST">
  <testcase classname="com.xcp.qa.testcases.Homepage_test" name="Homepagefun" time="1.677"/>
  <testcase classname="com.xcp.qa.testcases.BML_AddCutomer_test" name="verifyAddCustomerFunctionality" time="2.294"/>
  <testcase classname="com.xcp.qa.testcases.BML_AddCutomerinvalid_test" name="verifyAddCustomerFunctionality" time="1.952">
    <failure type="java.lang.AssertionError" message="Error message is not displayed for invalid data expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message is not displayed for invalid data expected [true] but found [false]
at com.xcp.qa.testcases.BML_AddCutomerinvalid_test.verifyAddCustomerFunctionality(BML_AddCutomerinvalid_test.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddCustomerFunctionality -->
  <testcase classname="com.xcp.qa.testcases.BML_OpenAC_test" name="OpenAccountCustomerTest" time="5.296"/>
  <testcase classname="com.xcp.qa.testcases.BML_Customers_test" name="OpenAccountCustomerTest" time="13.817"/>
  <testcase classname="com.xcp.qa.testcases.CL_customerdetails_test" name="CustomerDetails" time="6.737"/>
  <testcase classname="com.xcp.qa.testcases.CL_deposit_test" name="Deposit_test" time="12.167"/>
  <testcase classname="com.xcp.qa.testcases.CL_Withdrawl_test" name="Deposit_test" time="10.716"/>
  <testcase classname="com.xcp.qa.testcases.CL_transactions_test" name="Deposit_test" time="14.668"/>
</testsuite> <!-- XYZ Bank Test -->
